#!/usr/bin/env python3
"""Phase 3 Tooling: Automated AI Generation of Mock Corporate Knowledge Bases."""

import os
from dotenv import load_dotenv
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Ensure environment variables are loaded
load_dotenv()

# Setup local client connection layout
base_url = (os.getenv("ANTHROPIC_BASE_URL") or "http://localhost:11434").strip()
if "/v1" in base_url:
    base_url = base_url.replace("/v1/chat/completions", "").replace("/v1", "")
model_name = os.getenv("CLAUDE_MODEL", "qwen3.5:9b").strip()

llm = ChatOllama(
    base_url=base_url.strip("/"),
    model=model_name,
    temperature=0.7,
    reasoning=False
)

DOCUMENT_BLUEPRINTS = [
    {
        "filename": "nexusflow_architecture.txt",
        "topic": "System Network Architecture and Ports",
        "guidelines": "Specify that NexusFlow runs on core port 9443 (secured via TLS 1.3). The internal routing mesh uses service port 7070. The backend database layer is locked behind cluster IP 10.0.4.15."
    },
    {
        "filename": "nexusflow_troubleshooting.txt",
        "topic": "Error Logs and System Troubleshooting Rules",
        "guidelines": "Describe error code 'ERR_NEXUS_DISCONNECT' which indicates a database connection drops. The absolute remediation command is 'nexusctl --reconnect --force'. Storage tracking paths are hardcoded to '/var/log/nexusflow/system.log'."
    },
    {
        "filename": "nexusflow_security.txt",
        "topic": "Security Protocols and Access Control Limits",
        "guidelines": "Define that administrative console access requires multi-factor authentication (MFA). Bearer session tokens automatically expire after 15 minutes of idle time. Cross-Origin Resource Sharing (CORS) rules must restrict traffic exclusively to domains ending in '.nexusflow.internal'."
    },
    {
        "filename": "nexusflow_deployment.txt",
        "topic": "Server Hardware and Minimum Deployment Budgets",
        "guidelines": "State that production cluster deployments require a minimum of 32GB RAM and 8 vCPUs per node. Storage partitions must use SSD drives with minimum IOPS benchmarks of 10,000. Environmental deployment flag must be specified as 'NEXUS_ENV=production'."
    }
]

def compile_corporate_knowledge_base():
    print("\n-----------------------------------------")
    print("--- AI Mock Data Generation Pipeline ----")
    print("-----------------------------------------")
    
    # PATH RESOLUTION: Locate 'source_documents' nested directly inside 'local-llm-client'
    script_dir = os.path.dirname(os.path.abspath(__file__))
    doc_folder = os.path.join(script_dir, "source_documents")
    os.makedirs(doc_folder, exist_ok=True)
    
    prompt_template = ChatPromptTemplate.from_messages([
        ("system", """You are a professional technical writer compiling software operations metrics. 
        Generate a highly realistic, concise technical reference text block based on the subject and parameters provided.
        DO NOT write standard conversational fluff, introductions, or pleasantries. Jump straight into the reference documentation format.
        """),
        ("human", "Generate a technical reference manual sheet about:\nTopic: {topic}\nRequired Details to Include: {guidelines}")
    ])
    
    chain = prompt_template | llm | StrOutputParser()
    
    for i, doc in enumerate(DOCUMENT_BLUEPRINTS, start=1):
        print(f"🔄 LLM Generating File {i}/4: '{doc['filename']}'...")
        
        raw_manual_content = chain.invoke({
            "topic": doc["topic"],
            "guidelines": doc["guidelines"]
        })
        
        filepath = os.path.join(doc_folder, doc["filename"])
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(raw_manual_content.strip())
            
    print(f"\n✅ Knowledge base built! 4 custom files generated by LLM and saved inside '{doc_folder}'.")

if __name__ == "__main__":
    compile_corporate_knowledge_base()
